# Generated by Django 2.1.5 on 2021-05-11 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Photo',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='image',
            new_name='photo',
        ),
    ]
